### ISSUE TITLE
Alternative way to launch.

### ISSUE THREAD

**Issue by 1Snakel** [LordOfDragons/dragengine#1]
Would be possible to add a script to launch it from the current folder on linux?

**Comment by LordOfDragons** [comment]
Do you mean starting a *.delga file without installing the game engine at all? This is possible using the Live Launcher. You can find it at [https://dragondreams.ch/?page_id=152](https://dragondreams.ch/?page_id=152) or in the release section here on GitHub. The file is named "dragengine-live-1.0.zip".

The Live Launcher can run only one *.delga file. If you want to run the entire game engine and GUI Launcher from a directory without installing it then this can be done by setting environment parameters. If this is what you have in mind I can update the README with the script snippet to do so.

Let me know if any of these solutions is what you are looking for.

**Comment by 1Snakel** [comment]
yup, its a way to launch the engine. Thanks for the script.

**Comment by LordOfDragons** [comment]
I'm not sure I understand correctly. Launching the engine to play a game is done using the GUI launcher (`/usr/bin/delauncher-gui game.delga`) or the console launcher (`/usr/bin/delauncher-console run -f game.delga`).

Can you please explain to me exactly what you are trying to achieve? Then I can provide you with the appropriate solution.

**Comment by 1Snakel** [comment]
Edited, sorry for the typos.

**Comment by LordOfDragons** [comment]
I've added now a [source-able file](https://github.com/LordOfDragons/dragengine/blob/master/prepare_local_dir_mode.source) to the repository and update the README.

Now there is a little problem. In the current 1.0 release the shared game definition files used to create new projects have full path for their base directory. I've also changed the source code to turn these path relative so it works with the above mentioned source-able file. If you want to use this file with the current 1.0 release you have to apply a manual fix before you can continue.

Edit these two files:
- share/deigde/gamedefs/dragonscript_basic.degd
- share/deigde/gamedefs/dragonscript_imm.degd

Change the path in the <basePath>-tag to point to the correct location in your local directory. If done correctly it will work. Otherwise you have to wait for the 1.1 release which contains the fixes.

I will also set up in the upcoming days a nightly build synced to GitHub. This one will be usable too once ready.

Please let me know if this all is helpful to you.

**Comment by 1Snakel** [comment]
Perfect, thanks
